export const dashboard = <i className="fa-solid fa-chart-line"></i>
export const transactions = <i className="fa-solid fa-credit-card"></i>
export const categories = <i className="fa-solid fa-tags"></i>
export const accounts = <i className="fa-solid fa-wallet"></i>
export const settings = <i className="fa-solid fa-cog"></i>
export const logout = <i className="fa-solid fa-sign-out"></i>
export const trend = <i className="fa-solid fa-money-bill-trend-up"></i>
export const expenses = <i className="fa-solid fa-money-bill-transfer"></i>
export const money = <i className="fa-solid fa-money-bill"></i>
export const freelance = <i className="fa-solid fa-earth-americas"></i>
export const stocks = <i className="fa-solid fa-arrow-trend-up"></i>
export const bitcoin = <i className="fa-solid fa-bitcoin"></i>
export const piggy = <i className="fa-solid fa-piggy-bank"></i>
export const yt = <i class="fa-brands fa-youtube"></i>
export const card = <i className="fa-solid fa-cc-visa"></i>
export const users = <i className="fa-solid fa-users-between-liines"></i>
export const dollar = <i className="fa-solid fa-dollar-sign"></i>
export const calender = <i className="fa-solid fa-calander"></i>
export const comment = <i className="fa-solid fa-comment"></i>
export const plus = <i className="fa-solid fa-plus"></i>
export const trash = <i className="fa-solid fa-trash"></i>
export const signout = <i className="fa-solid fa-right-from-bracket"></i>
export const takeaway = <i className="fa-solid fa-utensils"></i>
export const clothing = <i className="fa-solid fa-shirt"></i>
export const book = <i className="fa-solid fa-book-open"></i>
export const food = <i className="fa-solid fa-bowl-food"></i>
export const medical = <i className="fa-solid fa-briefcase-medical"></i>
export const tv = <i className="fa-solid fa-tv"></i>
export const circle = <i className="fa-solid fa-corcle-dot"></i>
export const starters = <i class="fa-solid fa-drumstick-bite"></i>
export const user = <i class="fa-solid fa-user"></i>
export const plate = <i class="fa-solid fa-plate-wheat"></i>
export const drinks = <i class="fa-solid fa-mug-hot"></i>
export const desserts = <i class="fa-solid fa-cake-candles"></i>
export const bill = <i class="fa-solid fa-receipt"></i> 
export const cart = <i class="fa-solid fa-cart-shopping"></i>
export const burger = <i class="fa-solid fa-burger"></i>
export const deluser = <i class="fa-solid fa-user-slash fa-beat" style={{color: "#ff0000"}}></i>
